# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'iOSIntegrationFlutterModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static

  # Pods for iOSIntegrationFlutterModule

  target 'iOSIntegrationFlutterModuleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSIntegrationFlutterModuleUITests' do
    # Pods for testing
  end

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
